# Generated by Django 3.2.3 on 2021-05-30 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mahi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_suggestions', to='mahi_app.cause'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='mahi_app.cause'),
        ),
        migrations.AddField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_donations', to='mahi_app.cause'),
        ),
        migrations.AddField(
            model_name='donation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cause',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needy_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cause',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_causes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cause',
            name='tag',
            field=models.ManyToManyField(related_name='associated_tag', to='mahi_app.Tag'),
        ),
        migrations.AddField(
            model_name='cause',
            name='volunteer_request',
            field=models.ManyToManyField(blank=True, related_name='requested_causes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benchmarkmedia',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_media', to='mahi_app.cause'),
        ),
        migrations.AddField(
            model_name='activity',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_activities', to='mahi_app.cause'),
        ),
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_activities', to='mahi_app.volunteer'),
        ),
    ]
